// Code generated by '_gen'
package arm7

// block cache assigns and returns blocks to be used by jit

import (
	"fmt"

	"github.com/aabalke/gojit"
)

type BlockCache struct {
	Head, Tail *JitBlock
	Blocks     []*JitBlock
	SkipBlock  *JitBlock
}

type JitBlock struct {
	Skip      bool
	f         func()
	initPc    uint32
	finalOp   uint32
	Length    uint32
	assembler *gojit.Assembler

	Prev, Next *JitBlock

	Thumb bool
}

func InitBlockCache(capacity uint32, page_size int) *BlockCache {

	bc := &BlockCache{
		Blocks:    []*JitBlock{},
		Head:      &JitBlock{},
		Tail:      &JitBlock{},
		SkipBlock: &JitBlock{Skip: true},
	}

	for range capacity {
		bc.Blocks = append(bc.Blocks, &JitBlock{})
	}

	// head and tail are never directly used, just pivots for
	// head prev and tail next
	bc.Head.Next = bc.Tail
	bc.Tail.Prev = bc.Head

	for i := range len(bc.Blocks) {

		bc.Blocks[i].Prev = bc.Head
		bc.Blocks[i].Next = bc.Head.Next

		bc.Head.Next.Prev = bc.Blocks[i]
		bc.Head.Next = bc.Blocks[i]

		asm, err := gojit.New(page_size)
		if err != nil {
			panic(err)
		}

		if asm == nil {
			panic("bad asm init")
		}

		bc.Blocks[i].assembler = asm
	}

	return bc
}

func (bc *BlockCache) Close() {
	for i := range len(bc.Blocks) {
		bc.Blocks[i].assembler.Release()
	}
}

func (bc *BlockCache) String() string {

	// string, tail -> head pointers
	s := "B "
	for b := bc.Tail; ; {
		if b != bc.Tail && b != bc.Head {
			s += fmt.Sprintf("%p ", b)
		}
		b = b.Prev
		if b.Prev == nil {
			break
		}
	}

	return s + "\n"
}

func (bc *BlockCache) BlockString() string {

	// string, need tail and head included to match String()

	s := fmt.Sprintf("B %p ", bc.Tail)
	for i := range len(bc.Blocks) {
		s += fmt.Sprintf("%p ", bc.Blocks[i])
	}

	s += fmt.Sprintf("%p\n", bc.Head)
	return s
}

//go:inline
func (bc *BlockCache) setHead(block *JitBlock) {
	block.Prev = bc.Head
	block.Next = bc.Head.Next
	bc.Head.Next.Prev = block
	bc.Head.Next = block
}

//go:inline
func (bc *BlockCache) setTail(block *JitBlock) {
	block.Prev = bc.Tail.Prev
	block.Next = bc.Tail
	bc.Tail.Prev.Next = block
	bc.Tail.Prev = block
}

//go:inline
func (bc *BlockCache) remove(block *JitBlock) {
	prev := block.Prev
	next := block.Next
	prev.Next = next
	next.Prev = prev
}

//go:inline
func (bc *BlockCache) PopTail() *JitBlock {
	block := bc.Tail.Prev
	bc.remove(block)
	bc.setHead(block)
	return block
}

//go:inline
func (bc *BlockCache) PushHead(block *JitBlock) {
	bc.remove(block)
	bc.setHead(block)
}

//go:inline
func (bc *BlockCache) PushTail(block *JitBlock) {
	bc.remove(block)
	bc.setTail(block)
}

func (bc *BlockCache) AssignBlock(jit *Jit) *JitBlock {

	block := bc.PopTail()

	if inUse := block.Length != 0; inUse {
		// need to invalidate pc currently using block
		revokedPC := block.initPc
		page := jit.Pages[revokedPC>>jit.PageShift]
		if page != nil {
			page.Blocks[(revokedPC&jit.PageMask)>>1] = nil
		}
	}

	block.assembler.Off = 0
	block.initPc = 0
	block.Length = 0
	block.finalOp = 0
	block.f = nil

	return block
}

//go:inline
func (bc *BlockCache) TouchBlock(block *JitBlock) {
	bc.PushHead(block)
}

//go:inline
func (bc *BlockCache) InvalidateBlock(block *JitBlock) {
	bc.PushTail(block)
}
