// Code generated by '_gen'

package gameboy

func (gb *GameBoy) renderTilesDMG(scanline uint8) {

	var (
		scrollY   = gb.MemoryBus.IO[0x42]
		scrollX   = gb.MemoryBus.IO[0x43]
		windowY   = gb.MemoryBus.IO[0x4A]
		windowX   = int(gb.MemoryBus.IO[0x4B]) - 7
		useWindow = gb.Lcdc.WindowEnabled && windowY <= scanline
	)

	tileData := uint16(0x8000)
	if !gb.Lcdc.UnsignedTiles {
		tileData = 0x8800
	}

	winMemory := uint16(0x9800)
	if gb.Lcdc.AltWinMap {
		winMemory = 0x9C00
	}

	bgMemory := uint16(0x9800)
	if gb.Lcdc.AltBgMap {
		bgMemory = 0x9C00
	}

	for pixel := range width {

		var yPos uint8
		var xPos uint8
		if winSpace := useWindow && pixel >= windowX; winSpace {
			xPos = uint8((int(pixel) - windowX))
			yPos = uint8(scanline - windowY)
		} else {
			xPos = (uint8(pixel) + scrollX)
			yPos = uint8(scrollY + scanline)
		}

		tileRow := uint16(yPos/8) * 32
		tileCol := uint16(xPos / 8)
		tileAddr := tileRow + tileCol
		if useWindow && pixel >= windowX {
			tileAddr += winMemory - 0x8000
		} else {
			tileAddr += bgMemory - 0x8000
		}

		tileLocation := tileData - 0x8000
		if gb.Lcdc.UnsignedTiles {
			tileNum := int16(gb.MemoryBus.VRAM[0][tileAddr])
			tileLocation = tileLocation + uint16(tileNum*16)
		} else {
			tileNum := int(int8(gb.MemoryBus.VRAM[0][tileAddr]))
			tileLocation = uint16(int(tileLocation) + int((tileNum+128)*16))
		}

		line := (yPos & 7)

		addr := tileLocation + uint16(line<<1)

		data1 := gb.MemoryBus.VRAM[0][addr+0]
		data2 := gb.MemoryBus.VRAM[0][addr+1]

		colorBit := 7 - (xPos & 7)

		//colorNum := getVal(data2, uint8(colorBit))
		//colorNum <<= 1
		//colorNum |= getVal(data1, uint8(colorBit))
		colorNum := getColorVal(data2, data1, colorBit, colorBit)
		gb.pixelDrawn[pixel] = colorNum != 0

		if draw := !gb.bgPriority[pixel][scanline]; draw {
			gb.Screen[pixel][scanline] = gb.UnpackedMonoPals[0][colorNum]
		}

	}
}

func (gb *GameBoy) renderSpritesDMG(scanline int32) {

	var ySize int32 = 8
	if gb.Lcdc.DoubleHeight {
		ySize = 16
	}

	gb.spMinx = [width]int32{}
	var lineSprites = 0
	for sprite := range uint16(40) {
		index := sprite * 4

		yP := gb.MemoryBus.OAM[index]
		yPos := int32(yP) - 16

		if scanline < yPos || scanline >= (yPos+ySize) {
			continue
		}

		// Only 10 sprites are allowed to be displayed on each line
		if lineSprites >= 10 {
			break
		}
		lineSprites++

		var (
			xPos         = int32(gb.MemoryBus.OAM[index+1]) - 8
			tileLocation = gb.MemoryBus.OAM[index+2]
			attributes   = gb.MemoryBus.OAM[index+3]
			yFlip        = (attributes>>6)&1 != 0
			xFlip        = (attributes>>5)&1 != 0
			priority     = !((attributes>>7)&1 != 0)
		)

		// Set the line to draw based on if the sprite is flipped on the y
		line := scanline - yPos
		if yFlip {
			line = ySize - line - 1
		}

		dataAddress := (uint16(tileLocation) * 0x10) + uint16(line*2)

		data1 := gb.MemoryBus.VRAM[0][dataAddress]
		data2 := gb.MemoryBus.VRAM[0][dataAddress+1]

		for tilePixel := range uint8(8) {
			pixel := int16(xPos) + 7 - int16(tilePixel)
			if pixel < 0 || pixel >= width {
				continue
			}

			if gb.spMinx[pixel] != 0 && (gb.spMinx[pixel] <= int32(xPos)+SpritePriorityOffset) {
				continue
			}

			colorBit := tilePixel
			if xFlip {
				colorBit = byte(int8(colorBit-7) * -1)
			}

			//colorNum := getVal(data2, uint8(colorBit))
			//colorNum <<= 1
			//colorNum |= getVal(data1, uint8(colorBit))
			colorNum := getColorVal(data2, data1, colorBit, colorBit)

			if transparent := colorNum == 0; transparent {
				continue
			}

			drawPixel := (priority && !gb.bgPriority[pixel][scanline]) || !gb.pixelDrawn[pixel]
			if drawPixel {

				pal := UNPACKED_OBJ0
				if (attributes>>4)&1 != 0 {
					pal = UNPACKED_OBJ1
				}

				gb.Screen[pixel][scanline] = gb.UnpackedMonoPals[pal][colorNum]

			}

			gb.spMinx[pixel] = int32(xPos) + SpritePriorityOffset
		}
	}
}
