#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev 2>/dev/null || true

mkdir -p /bin /sbin /usr/bin /usr/sbin
mkdir -p /host
mount -t hostfs none /host -o /

/bin/busybox --install -s

#bring up the network
netup
#turn on loopback interface for 127.0.0.1
ifconfig lo up

echo ""
echo "=== RISC-V initramfs booted ==="
echo ""
exec /bin/busybox setsid /bin/sh -c 'exec /bin/sh -i </dev/ttyS0 >/dev/ttyS0 2>&1'
