// Code generated by GREENPACK (github.com/glycerine/greenpack). DO NOT EDIT.

package emunet

import (
	"fmt"

	"github.com/glycerine/greenpack/msgp"
)

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *EmunetDNS) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields1zgensym_20a43f99f8f675c7_2 = 2

	// -- templateDecodeMsg starts here--
	var totalEncodedFields1zgensym_20a43f99f8f675c7_2 uint32
	totalEncodedFields1zgensym_20a43f99f8f675c7_2, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft1zgensym_20a43f99f8f675c7_2 := totalEncodedFields1zgensym_20a43f99f8f675c7_2
	missingFieldsLeft1zgensym_20a43f99f8f675c7_2 := maxFields1zgensym_20a43f99f8f675c7_2 - totalEncodedFields1zgensym_20a43f99f8f675c7_2

	var nextMiss1zgensym_20a43f99f8f675c7_2 int32 = -1
	var found1zgensym_20a43f99f8f675c7_2 [maxFields1zgensym_20a43f99f8f675c7_2]bool
	var curField1zgensym_20a43f99f8f675c7_2 string

doneWithStruct1zgensym_20a43f99f8f675c7_2:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft1zgensym_20a43f99f8f675c7_2 > 0 || missingFieldsLeft1zgensym_20a43f99f8f675c7_2 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft1zgensym_20a43f99f8f675c7_2, missingFieldsLeft1zgensym_20a43f99f8f675c7_2, msgp.ShowFound(found1zgensym_20a43f99f8f675c7_2[:]), decodeMsgFieldOrder1zgensym_20a43f99f8f675c7_2)
		if encodedFieldsLeft1zgensym_20a43f99f8f675c7_2 > 0 {
			encodedFieldsLeft1zgensym_20a43f99f8f675c7_2--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField1zgensym_20a43f99f8f675c7_2 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss1zgensym_20a43f99f8f675c7_2 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss1zgensym_20a43f99f8f675c7_2 = 0
			}
			for nextMiss1zgensym_20a43f99f8f675c7_2 < maxFields1zgensym_20a43f99f8f675c7_2 && (found1zgensym_20a43f99f8f675c7_2[nextMiss1zgensym_20a43f99f8f675c7_2] || decodeMsgFieldSkip1zgensym_20a43f99f8f675c7_2[nextMiss1zgensym_20a43f99f8f675c7_2]) {
				nextMiss1zgensym_20a43f99f8f675c7_2++
			}
			if nextMiss1zgensym_20a43f99f8f675c7_2 == maxFields1zgensym_20a43f99f8f675c7_2 {
				// filled all the empty fields!
				break doneWithStruct1zgensym_20a43f99f8f675c7_2
			}
			missingFieldsLeft1zgensym_20a43f99f8f675c7_2--
			curField1zgensym_20a43f99f8f675c7_2 = decodeMsgFieldOrder1zgensym_20a43f99f8f675c7_2[nextMiss1zgensym_20a43f99f8f675c7_2]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField1zgensym_20a43f99f8f675c7_2)
		switch curField1zgensym_20a43f99f8f675c7_2 {
		// -- templateDecodeMsg ends here --

		case "LeaderURL_zid00_str":
			found1zgensym_20a43f99f8f675c7_2[0] = true
			z.LeaderURL, err = dc.ReadString()
			if err != nil {
				return
			}
		case "KnownFollowerURLs_zid01_slc":
			found1zgensym_20a43f99f8f675c7_2[1] = true
			var zgensym_20a43f99f8f675c7_3 uint32
			zgensym_20a43f99f8f675c7_3, err = dc.ReadArrayHeader()
			if err != nil {
				return
			}
			if cap(z.KnownFollowerURLs) >= int(zgensym_20a43f99f8f675c7_3) {
				z.KnownFollowerURLs = (z.KnownFollowerURLs)[:zgensym_20a43f99f8f675c7_3]
			} else {
				z.KnownFollowerURLs = make([]string, zgensym_20a43f99f8f675c7_3)
			}
			for zgensym_20a43f99f8f675c7_0 := range z.KnownFollowerURLs {
				z.KnownFollowerURLs[zgensym_20a43f99f8f675c7_0], err = dc.ReadString()
				if err != nil {
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss1zgensym_20a43f99f8f675c7_2 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of EmunetDNS
var decodeMsgFieldOrder1zgensym_20a43f99f8f675c7_2 = []string{"LeaderURL_zid00_str", "KnownFollowerURLs_zid01_slc"}

var decodeMsgFieldSkip1zgensym_20a43f99f8f675c7_2 = []bool{false, false}

// fieldsNotEmpty supports omitempty tags
func (z *EmunetDNS) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 2
	}
	var fieldsInUse uint32 = 2
	isempty[0] = (len(z.LeaderURL) == 0) // string, omitempty
	if isempty[0] {
		fieldsInUse--
	}
	isempty[1] = (len(z.KnownFollowerURLs) == 0) // string, omitempty
	if isempty[1] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *EmunetDNS) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_20a43f99f8f675c7_4 [2]bool
	fieldsInUse_zgensym_20a43f99f8f675c7_5 := z.fieldsNotEmpty(empty_zgensym_20a43f99f8f675c7_4[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_20a43f99f8f675c7_5 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'EmunetDNS'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x45, 0x6d, 0x75, 0x6e, 0x65, 0x74, 0x44, 0x4e, 0x53})
	if err != nil {
		return err
	}

	if !empty_zgensym_20a43f99f8f675c7_4[0] {
		// write "LeaderURL_zid00_str"
		err = en.Append(0xb3, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.LeaderURL)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_20a43f99f8f675c7_4[1] {
		// write "KnownFollowerURLs_zid01_slc"
		err = en.Append(0xbb, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x73, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x73, 0x6c, 0x63)
		if err != nil {
			return err
		}
		err = en.WriteArrayHeader(uint32(len(z.KnownFollowerURLs)))
		if err != nil {
			return
		}
		for zgensym_20a43f99f8f675c7_0 := range z.KnownFollowerURLs {
			err = en.WriteString(z.KnownFollowerURLs[zgensym_20a43f99f8f675c7_0])
			if err != nil {
				return
			}
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *EmunetDNS) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [2]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "LeaderURL_zid00_str"
		o = append(o, 0xb3, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.LeaderURL)
	}

	if !empty[1] {
		// string "KnownFollowerURLs_zid01_slc"
		o = append(o, 0xbb, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x73, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x73, 0x6c, 0x63)
		o = msgp.AppendArrayHeader(o, uint32(len(z.KnownFollowerURLs)))
		for zgensym_20a43f99f8f675c7_0 := range z.KnownFollowerURLs {
			o = msgp.AppendString(o, z.KnownFollowerURLs[zgensym_20a43f99f8f675c7_0])
		}
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *EmunetDNS) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *EmunetDNS) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields6zgensym_20a43f99f8f675c7_7 = 2

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields6zgensym_20a43f99f8f675c7_7 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields6zgensym_20a43f99f8f675c7_7, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft6zgensym_20a43f99f8f675c7_7 := totalEncodedFields6zgensym_20a43f99f8f675c7_7
	missingFieldsLeft6zgensym_20a43f99f8f675c7_7 := maxFields6zgensym_20a43f99f8f675c7_7 - totalEncodedFields6zgensym_20a43f99f8f675c7_7

	var nextMiss6zgensym_20a43f99f8f675c7_7 int32 = -1
	var found6zgensym_20a43f99f8f675c7_7 [maxFields6zgensym_20a43f99f8f675c7_7]bool
	var curField6zgensym_20a43f99f8f675c7_7 string

doneWithStruct6zgensym_20a43f99f8f675c7_7:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft6zgensym_20a43f99f8f675c7_7 > 0 || missingFieldsLeft6zgensym_20a43f99f8f675c7_7 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft6zgensym_20a43f99f8f675c7_7, missingFieldsLeft6zgensym_20a43f99f8f675c7_7, msgp.ShowFound(found6zgensym_20a43f99f8f675c7_7[:]), unmarshalMsgFieldOrder6zgensym_20a43f99f8f675c7_7)
		if encodedFieldsLeft6zgensym_20a43f99f8f675c7_7 > 0 {
			encodedFieldsLeft6zgensym_20a43f99f8f675c7_7--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField6zgensym_20a43f99f8f675c7_7 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss6zgensym_20a43f99f8f675c7_7 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss6zgensym_20a43f99f8f675c7_7 = 0
			}
			for nextMiss6zgensym_20a43f99f8f675c7_7 < maxFields6zgensym_20a43f99f8f675c7_7 && (found6zgensym_20a43f99f8f675c7_7[nextMiss6zgensym_20a43f99f8f675c7_7] || unmarshalMsgFieldSkip6zgensym_20a43f99f8f675c7_7[nextMiss6zgensym_20a43f99f8f675c7_7]) {
				nextMiss6zgensym_20a43f99f8f675c7_7++
			}
			if nextMiss6zgensym_20a43f99f8f675c7_7 == maxFields6zgensym_20a43f99f8f675c7_7 {
				// filled all the empty fields!
				break doneWithStruct6zgensym_20a43f99f8f675c7_7
			}
			missingFieldsLeft6zgensym_20a43f99f8f675c7_7--
			curField6zgensym_20a43f99f8f675c7_7 = unmarshalMsgFieldOrder6zgensym_20a43f99f8f675c7_7[nextMiss6zgensym_20a43f99f8f675c7_7]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField6zgensym_20a43f99f8f675c7_7)
		switch curField6zgensym_20a43f99f8f675c7_7 {
		// -- templateUnmarshalMsg ends here --

		case "LeaderURL_zid00_str":
			found6zgensym_20a43f99f8f675c7_7[0] = true
			z.LeaderURL, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		case "KnownFollowerURLs_zid01_slc":
			found6zgensym_20a43f99f8f675c7_7[1] = true
			if nbs.AlwaysNil {
				(z.KnownFollowerURLs) = (z.KnownFollowerURLs)[:0]
			} else {

				var zgensym_20a43f99f8f675c7_8 uint32
				zgensym_20a43f99f8f675c7_8, bts, err = nbs.ReadArrayHeaderBytes(bts)
				if err != nil {
					return
				}
				if cap(z.KnownFollowerURLs) >= int(zgensym_20a43f99f8f675c7_8) {
					z.KnownFollowerURLs = (z.KnownFollowerURLs)[:zgensym_20a43f99f8f675c7_8]
				} else {
					z.KnownFollowerURLs = make([]string, zgensym_20a43f99f8f675c7_8)
				}
				for zgensym_20a43f99f8f675c7_0 := range z.KnownFollowerURLs {
					z.KnownFollowerURLs[zgensym_20a43f99f8f675c7_0], bts, err = nbs.ReadStringBytes(bts)

					if err != nil {
						return
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss6zgensym_20a43f99f8f675c7_7 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of EmunetDNS
var unmarshalMsgFieldOrder6zgensym_20a43f99f8f675c7_7 = []string{"LeaderURL_zid00_str", "KnownFollowerURLs_zid01_slc"}

var unmarshalMsgFieldSkip6zgensym_20a43f99f8f675c7_7 = []bool{false, false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *EmunetDNS) Msgsize() (s int) {
	s = 1 + 20 + msgp.StringPrefixSize + len(z.LeaderURL) + 28 + msgp.ArrayHeaderSize
	for zgensym_20a43f99f8f675c7_0 := range z.KnownFollowerURLs {
		s += msgp.StringPrefixSize + len(z.KnownFollowerURLs[zgensym_20a43f99f8f675c7_0])
	}
	return
}
func (z *EmunetDNS) Gstring() (r string) {
	r = "&EmunetDNS{\n"
	r += fmt.Sprintf("        LeaderURL: \"%v\",\n", z.LeaderURL)
	r += fmt.Sprintf("KnownFollowerURLs: %v,\n", z.KnownFollowerURLs)
	r += "}\n"
	return
}

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *Message) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields9zgensym_20a43f99f8f675c7_10 = 8

	// -- templateDecodeMsg starts here--
	var totalEncodedFields9zgensym_20a43f99f8f675c7_10 uint32
	totalEncodedFields9zgensym_20a43f99f8f675c7_10, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft9zgensym_20a43f99f8f675c7_10 := totalEncodedFields9zgensym_20a43f99f8f675c7_10
	missingFieldsLeft9zgensym_20a43f99f8f675c7_10 := maxFields9zgensym_20a43f99f8f675c7_10 - totalEncodedFields9zgensym_20a43f99f8f675c7_10

	var nextMiss9zgensym_20a43f99f8f675c7_10 int32 = -1
	var found9zgensym_20a43f99f8f675c7_10 [maxFields9zgensym_20a43f99f8f675c7_10]bool
	var curField9zgensym_20a43f99f8f675c7_10 string

doneWithStruct9zgensym_20a43f99f8f675c7_10:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft9zgensym_20a43f99f8f675c7_10 > 0 || missingFieldsLeft9zgensym_20a43f99f8f675c7_10 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft9zgensym_20a43f99f8f675c7_10, missingFieldsLeft9zgensym_20a43f99f8f675c7_10, msgp.ShowFound(found9zgensym_20a43f99f8f675c7_10[:]), decodeMsgFieldOrder9zgensym_20a43f99f8f675c7_10)
		if encodedFieldsLeft9zgensym_20a43f99f8f675c7_10 > 0 {
			encodedFieldsLeft9zgensym_20a43f99f8f675c7_10--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField9zgensym_20a43f99f8f675c7_10 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss9zgensym_20a43f99f8f675c7_10 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss9zgensym_20a43f99f8f675c7_10 = 0
			}
			for nextMiss9zgensym_20a43f99f8f675c7_10 < maxFields9zgensym_20a43f99f8f675c7_10 && (found9zgensym_20a43f99f8f675c7_10[nextMiss9zgensym_20a43f99f8f675c7_10] || decodeMsgFieldSkip9zgensym_20a43f99f8f675c7_10[nextMiss9zgensym_20a43f99f8f675c7_10]) {
				nextMiss9zgensym_20a43f99f8f675c7_10++
			}
			if nextMiss9zgensym_20a43f99f8f675c7_10 == maxFields9zgensym_20a43f99f8f675c7_10 {
				// filled all the empty fields!
				break doneWithStruct9zgensym_20a43f99f8f675c7_10
			}
			missingFieldsLeft9zgensym_20a43f99f8f675c7_10--
			curField9zgensym_20a43f99f8f675c7_10 = decodeMsgFieldOrder9zgensym_20a43f99f8f675c7_10[nextMiss9zgensym_20a43f99f8f675c7_10]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField9zgensym_20a43f99f8f675c7_10)
		switch curField9zgensym_20a43f99f8f675c7_10 {
		// -- templateDecodeMsg ends here --

		case "Version_zid00_int":
			found9zgensym_20a43f99f8f675c7_10[0] = true
			z.Version, err = dc.ReadInt()
			if err != nil {
				return
			}
		case "Kind_zid01_str":
			found9zgensym_20a43f99f8f675c7_10[1] = true
			z.Kind, err = dc.ReadString()
			if err != nil {
				return
			}
		case "NodeID_zid02_str":
			found9zgensym_20a43f99f8f675c7_10[2] = true
			z.NodeID, err = dc.ReadString()
			if err != nil {
				return
			}
		case "PeerURL_zid03_str":
			found9zgensym_20a43f99f8f675c7_10[3] = true
			z.PeerURL, err = dc.ReadString()
			if err != nil {
				return
			}
		case "MAC_zid04_bin":
			found9zgensym_20a43f99f8f675c7_10[4] = true
			z.MAC, err = dc.ReadBytes(z.MAC)
			if err != nil {
				return
			}
		case "LeaderURL_zid05_str":
			found9zgensym_20a43f99f8f675c7_10[5] = true
			z.LeaderURL, err = dc.ReadString()
			if err != nil {
				return
			}
		case "Error_zid06_str":
			found9zgensym_20a43f99f8f675c7_10[6] = true
			z.Error, err = dc.ReadString()
			if err != nil {
				return
			}
		case "Frame_zid07_bin":
			found9zgensym_20a43f99f8f675c7_10[7] = true
			z.Frame, err = dc.ReadBytes(z.Frame)
			if err != nil {
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss9zgensym_20a43f99f8f675c7_10 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of Message
var decodeMsgFieldOrder9zgensym_20a43f99f8f675c7_10 = []string{"Version_zid00_int", "Kind_zid01_str", "NodeID_zid02_str", "PeerURL_zid03_str", "MAC_zid04_bin", "LeaderURL_zid05_str", "Error_zid06_str", "Frame_zid07_bin"}

var decodeMsgFieldSkip9zgensym_20a43f99f8f675c7_10 = []bool{false, false, false, false, false, false, false, false}

// fieldsNotEmpty supports omitempty tags
func (z *Message) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 8
	}
	var fieldsInUse uint32 = 8
	isempty[0] = (z.Version == 0) // number, omitempty
	if isempty[0] {
		fieldsInUse--
	}
	isempty[1] = (len(z.Kind) == 0) // string, omitempty
	if isempty[1] {
		fieldsInUse--
	}
	isempty[2] = (len(z.NodeID) == 0) // string, omitempty
	if isempty[2] {
		fieldsInUse--
	}
	isempty[3] = (len(z.PeerURL) == 0) // string, omitempty
	if isempty[3] {
		fieldsInUse--
	}
	isempty[4] = (len(z.MAC) == 0) // string, omitempty
	if isempty[4] {
		fieldsInUse--
	}
	isempty[5] = (len(z.LeaderURL) == 0) // string, omitempty
	if isempty[5] {
		fieldsInUse--
	}
	isempty[6] = (len(z.Error) == 0) // string, omitempty
	if isempty[6] {
		fieldsInUse--
	}
	isempty[7] = (len(z.Frame) == 0) // string, omitempty
	if isempty[7] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *Message) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_20a43f99f8f675c7_11 [8]bool
	fieldsInUse_zgensym_20a43f99f8f675c7_12 := z.fieldsNotEmpty(empty_zgensym_20a43f99f8f675c7_11[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_20a43f99f8f675c7_12 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'Message'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65})
	if err != nil {
		return err
	}

	if !empty_zgensym_20a43f99f8f675c7_11[0] {
		// write "Version_zid00_int"
		err = en.Append(0xb1, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x69, 0x6e, 0x74)
		if err != nil {
			return err
		}
		err = en.WriteInt(z.Version)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_20a43f99f8f675c7_11[1] {
		// write "Kind_zid01_str"
		err = en.Append(0xae, 0x4b, 0x69, 0x6e, 0x64, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.Kind)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_20a43f99f8f675c7_11[2] {
		// write "NodeID_zid02_str"
		err = en.Append(0xb0, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.NodeID)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_20a43f99f8f675c7_11[3] {
		// write "PeerURL_zid03_str"
		err = en.Append(0xb1, 0x50, 0x65, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x33, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.PeerURL)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_20a43f99f8f675c7_11[4] {
		// write "MAC_zid04_bin"
		err = en.Append(0xad, 0x4d, 0x41, 0x43, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x34, 0x5f, 0x62, 0x69, 0x6e)
		if err != nil {
			return err
		}
		err = en.WriteBytes(z.MAC)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_20a43f99f8f675c7_11[5] {
		// write "LeaderURL_zid05_str"
		err = en.Append(0xb3, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x35, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.LeaderURL)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_20a43f99f8f675c7_11[6] {
		// write "Error_zid06_str"
		err = en.Append(0xaf, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x36, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.Error)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_20a43f99f8f675c7_11[7] {
		// write "Frame_zid07_bin"
		err = en.Append(0xaf, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x37, 0x5f, 0x62, 0x69, 0x6e)
		if err != nil {
			return err
		}
		err = en.WriteBytes(z.Frame)
		if err != nil {
			return
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Message) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [8]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "Version_zid00_int"
		o = append(o, 0xb1, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x69, 0x6e, 0x74)
		o = msgp.AppendInt(o, z.Version)
	}

	if !empty[1] {
		// string "Kind_zid01_str"
		o = append(o, 0xae, 0x4b, 0x69, 0x6e, 0x64, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.Kind)
	}

	if !empty[2] {
		// string "NodeID_zid02_str"
		o = append(o, 0xb0, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.NodeID)
	}

	if !empty[3] {
		// string "PeerURL_zid03_str"
		o = append(o, 0xb1, 0x50, 0x65, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x33, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.PeerURL)
	}

	if !empty[4] {
		// string "MAC_zid04_bin"
		o = append(o, 0xad, 0x4d, 0x41, 0x43, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x34, 0x5f, 0x62, 0x69, 0x6e)
		o = msgp.AppendBytes(o, z.MAC)
	}

	if !empty[5] {
		// string "LeaderURL_zid05_str"
		o = append(o, 0xb3, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x35, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.LeaderURL)
	}

	if !empty[6] {
		// string "Error_zid06_str"
		o = append(o, 0xaf, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x36, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.Error)
	}

	if !empty[7] {
		// string "Frame_zid07_bin"
		o = append(o, 0xaf, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x37, 0x5f, 0x62, 0x69, 0x6e)
		o = msgp.AppendBytes(o, z.Frame)
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Message) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *Message) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields13zgensym_20a43f99f8f675c7_14 = 8

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields13zgensym_20a43f99f8f675c7_14 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields13zgensym_20a43f99f8f675c7_14, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft13zgensym_20a43f99f8f675c7_14 := totalEncodedFields13zgensym_20a43f99f8f675c7_14
	missingFieldsLeft13zgensym_20a43f99f8f675c7_14 := maxFields13zgensym_20a43f99f8f675c7_14 - totalEncodedFields13zgensym_20a43f99f8f675c7_14

	var nextMiss13zgensym_20a43f99f8f675c7_14 int32 = -1
	var found13zgensym_20a43f99f8f675c7_14 [maxFields13zgensym_20a43f99f8f675c7_14]bool
	var curField13zgensym_20a43f99f8f675c7_14 string

doneWithStruct13zgensym_20a43f99f8f675c7_14:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft13zgensym_20a43f99f8f675c7_14 > 0 || missingFieldsLeft13zgensym_20a43f99f8f675c7_14 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft13zgensym_20a43f99f8f675c7_14, missingFieldsLeft13zgensym_20a43f99f8f675c7_14, msgp.ShowFound(found13zgensym_20a43f99f8f675c7_14[:]), unmarshalMsgFieldOrder13zgensym_20a43f99f8f675c7_14)
		if encodedFieldsLeft13zgensym_20a43f99f8f675c7_14 > 0 {
			encodedFieldsLeft13zgensym_20a43f99f8f675c7_14--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField13zgensym_20a43f99f8f675c7_14 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss13zgensym_20a43f99f8f675c7_14 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss13zgensym_20a43f99f8f675c7_14 = 0
			}
			for nextMiss13zgensym_20a43f99f8f675c7_14 < maxFields13zgensym_20a43f99f8f675c7_14 && (found13zgensym_20a43f99f8f675c7_14[nextMiss13zgensym_20a43f99f8f675c7_14] || unmarshalMsgFieldSkip13zgensym_20a43f99f8f675c7_14[nextMiss13zgensym_20a43f99f8f675c7_14]) {
				nextMiss13zgensym_20a43f99f8f675c7_14++
			}
			if nextMiss13zgensym_20a43f99f8f675c7_14 == maxFields13zgensym_20a43f99f8f675c7_14 {
				// filled all the empty fields!
				break doneWithStruct13zgensym_20a43f99f8f675c7_14
			}
			missingFieldsLeft13zgensym_20a43f99f8f675c7_14--
			curField13zgensym_20a43f99f8f675c7_14 = unmarshalMsgFieldOrder13zgensym_20a43f99f8f675c7_14[nextMiss13zgensym_20a43f99f8f675c7_14]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField13zgensym_20a43f99f8f675c7_14)
		switch curField13zgensym_20a43f99f8f675c7_14 {
		// -- templateUnmarshalMsg ends here --

		case "Version_zid00_int":
			found13zgensym_20a43f99f8f675c7_14[0] = true
			z.Version, bts, err = nbs.ReadIntBytes(bts)

			if err != nil {
				return
			}
		case "Kind_zid01_str":
			found13zgensym_20a43f99f8f675c7_14[1] = true
			z.Kind, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		case "NodeID_zid02_str":
			found13zgensym_20a43f99f8f675c7_14[2] = true
			z.NodeID, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		case "PeerURL_zid03_str":
			found13zgensym_20a43f99f8f675c7_14[3] = true
			z.PeerURL, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		case "MAC_zid04_bin":
			found13zgensym_20a43f99f8f675c7_14[4] = true
			if nbs.AlwaysNil || msgp.IsNil(bts) {
				if !nbs.AlwaysNil {
					bts = bts[1:]
				}
				z.MAC = z.MAC[:0]
			} else {
				z.MAC, bts, err = nbs.ReadBytesBytes(bts, z.MAC)

				if err != nil {
					return
				}
			}
			if err != nil {
				return
			}
		case "LeaderURL_zid05_str":
			found13zgensym_20a43f99f8f675c7_14[5] = true
			z.LeaderURL, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		case "Error_zid06_str":
			found13zgensym_20a43f99f8f675c7_14[6] = true
			z.Error, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		case "Frame_zid07_bin":
			found13zgensym_20a43f99f8f675c7_14[7] = true
			if nbs.AlwaysNil || msgp.IsNil(bts) {
				if !nbs.AlwaysNil {
					bts = bts[1:]
				}
				z.Frame = z.Frame[:0]
			} else {
				z.Frame, bts, err = nbs.ReadBytesBytes(bts, z.Frame)

				if err != nil {
					return
				}
			}
			if err != nil {
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss13zgensym_20a43f99f8f675c7_14 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of Message
var unmarshalMsgFieldOrder13zgensym_20a43f99f8f675c7_14 = []string{"Version_zid00_int", "Kind_zid01_str", "NodeID_zid02_str", "PeerURL_zid03_str", "MAC_zid04_bin", "LeaderURL_zid05_str", "Error_zid06_str", "Frame_zid07_bin"}

var unmarshalMsgFieldSkip13zgensym_20a43f99f8f675c7_14 = []bool{false, false, false, false, false, false, false, false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Message) Msgsize() (s int) {
	s = 1 + 18 + msgp.IntSize + 15 + msgp.StringPrefixSize + len(z.Kind) + 17 + msgp.StringPrefixSize + len(z.NodeID) + 18 + msgp.StringPrefixSize + len(z.PeerURL) + 14 + msgp.BytesPrefixSize + len(z.MAC) + 20 + msgp.StringPrefixSize + len(z.LeaderURL) + 16 + msgp.StringPrefixSize + len(z.Error) + 16 + msgp.BytesPrefixSize + len(z.Frame)
	return
}
func (z *Message) Gstring() (r string) {
	r = "&Message{\n"
	r += fmt.Sprintf("  Version: %v,\n", z.Version)
	r += fmt.Sprintf("     Kind: \"%v\",\n", z.Kind)
	r += fmt.Sprintf("   NodeID: \"%v\",\n", z.NodeID)
	r += fmt.Sprintf("  PeerURL: \"%v\",\n", z.PeerURL)
	r += fmt.Sprintf("      MAC: %v,\n", z.MAC)
	r += fmt.Sprintf("LeaderURL: \"%v\",\n", z.LeaderURL)
	r += fmt.Sprintf("    Error: \"%v\",\n", z.Error)
	r += fmt.Sprintf("    Frame: %v,\n", z.Frame)
	r += "}\n"
	return
}
