# keyboard ids come from ebitengine string values.
# gamepad / controller ids: https://www.w3.org/TR/gamepad/#remapping

# only cancel audio init for profiling / benchmarking
# cancel_audio_init = true

vsync_disabled = true

#fullscreen = true
backdrop_color = 0x0A0A0A

# Define how many games appear per row on game select screen
games_per_row = 6

[mouse]

fill = true
stroke = true
unselected_alpha = 0.5
cursor_diameter = 8
stroke_width = 2
fill_color = 0xFFFFFF
stroke_color = 0x000000

[keyboard]
select     = ["J", "Enter"]
mute       = ["M"]
pause      = ["P"]
quit       = ["Q"]
fullscreen = ["F11"]
left       = ["A", "ArrowLeft"]
right      = ["D", "ArrowRight"]
up         = ["W", "ArrowUp"]
down       = ["S", "ArrowDown"]

# unlimited is limited to 65536 fps
# Buttons used to toggle different fps
unlimited  = ["U"]
fps15      = ["Numpad1"]
fps30      = ["Numpad2"]
fps60      = ["Numpad3"]
fps120     = ["Numpad4"]
fps180     = ["Numpad5"]
fps240     = ["Numpad6"]

[controller]
select = [1]
mute   = [8]
pause  = [9]
left   = [14]
right  = [15]
up     = [12]
down   = [13]

[jit]

# jit (just in time compilation) converts emulated machine code into native machine code when loops are detected. This increases the speed significantly but can ruin accuracy.
# jit only supports amd64 (64 bit x86 instruction set)
# jit only works for nds, gba is too time sensitive at this time

enabled = true

# how many times a loop occurs before jitting
loop_cnt = 255

# cnt of jit blocks in cache (per cpu)
block_cnt = 0x1000

page_shift = 16

# how many instructions to batch at a time (use 16, or 32 for best results)
# to many will cause crashes and artificants by desyncing cpus from sound and graphics
batch_inst = 32

# GB Configuration

[gb]
# Define a 4 color palette to replace greyscale using hex values
# From lightest -> darkest
# if invalid input, will fall back to greyscale
# dmg_palette = [ 0xE0F8D0, 0x88C070, 0x346856, 0x081820 ]

# forces "dmg", "gbc" or "auto" version for reading rom
type = "auto"

[gb.keyboard]

a = ["J"]
b = ["K"]
select = ["L"]
start = ["Semicolon"]
left = ["A"]
right = ["D"]
up = ["W"]
down = ["S"]

[gb.controller]
a = [1]
b = [0]
select = [2]
start = [3]
left = [14]
right = [15]
up = [12]
down = [13]

# GBA Configuration

[gba]

# Experimental options which may cause crashes or glitches
#skip_hle = true 
#threads = 8
idle_optimize = true

# set between 0x100 - 0x400 to set how often the sound clock is updated
# lower is more often, which is great for quality
# higher is better for lower end systems that cannot render sound fast enough
sound_clock_update_cycles = 0x100

#disable_saves = true

[gba.keyboard]
a = ["J"]
b = ["K"]
select = ["L"]
start = ["Semicolon"]
left = ["A"]
right = ["D"]
up = ["W"]
down = ["S"]
r = ["Y"]
l = ["T"]

[gba.controller]
a = [1]
b = [0]
select = [2]
start = [3]
left = [14]
right = [15]
up = [12]
down = [13]
r = [5]
l = [4]

# NDS Configuration

[nds]

[nds.bios]

# Nds bios is not necessary. The Drastic ARM7/ARM9 BIOS Replacements are provided. If you have your own bios files you can include them here.

#arm7_path = "./rom/bios/bios7.bin"
#arm9_path = "./rom/bios/bios9.bin"

[nds.screen]

# Hybrid is special mode showing a large screen and both screens to the side.
# Hybrid cannot be rotated. If Hybrid and sizing is "only bottom", large screen
# will be bottom and touch input will be on main screen instead of secondary.

layout = "vertical" # "vertical", "horizontal", "Hybrid"
sizing = "even"     # "even", "only top", "only bottom"
rotation = 0        # 0, 90, 180, 270

[nds.keyboard]
a = ["J"]
b = ["K"]
select = ["L"]
start = ["Semicolon"]
left = ["A"]
right = ["D"]
up = ["W"]
down = ["S"]
r = ["Y"]
l = ["T"]
x = ["U"]
y = ["I"]
hinge = ["O"]
debug = ["M"]

# these will increment through selected screen options.
layout_toggle = ["F1"]
sizing_toggle = ["F2"]
rotation_toggle = ["F3"]

export_scene = ["F4"]

[nds.controller]
a = [1]
b = [0]
select = [10]
start = [11]
left = [14]
right = [15]
up = [12]
down = [13]
r = [5]
l = [4]
x = [3]
y = [2]

[nds.firmware]

#file_path = "./rom/bios/firmware.bin"

# nickname = "guac"
# message = "This is a message."
# Gray, Brown, Red, Pink, Orange, Yellow, LimeGreen, Green, DarkGreen, SeaGreen,
# Turquoise, Blue, DarkBlue, DarkPurple, Violet, Magenta
# favorite_color = "Pink"


[nds.rtc]
# real time clock uses your current time, you can add hours to skip to different times of day. ex if real time is 9pm. add 11 hours sets rtc to 8am.
# additional_hours = 6 

[nds.export]
# allows 3d scene to exported to obj/mtl file formats.
# also exports all textures in active scene as pngs
# useful for debugging, and preservation.

# Obj export is basic and does not support texture blending, texture clamping,
# repeat, or flipping. It's mostly for meshes.
directory = "./export/"
file_type = "obj"
shadow_polygons = false
